server.port=${SERVER_PORT:8080}

# Quorum parameters
replica.n=${N:3}
replica.w=${W:2}
replica.r=${R:2}

# Comma-separated URLs of ALL replicas (including self)
replica.peers=${REPLICAS:http://localhost:8080}

# Max random replication delay in ms
replica.replication-delay-max-ms=${REPLICATION_DELAY_MAX_MS:1000}

# Reduce Spring noise in logs
logging.level.root=WARN
logging.level.com.lab=INFO
